<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="uat"
    errors="1" failures="0" hostname="" id="" package="uat" skipped="0"
    tests="1" time="0.007000" timestamp="Mon, 30 Jul 2018 12:24:40 GMT">
  
    <testcase name="logowanie uat" classname="uat" time="0.007000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Uat / logowanie uat]:

  ReferenceError: mask is not defined
    at Object.logowanie uat (C:\Users\UP68ER\Projects\testy\test\uat.js:9:20)
    at Module.call (C:\Users\UP68ER\Projects\testy\node_modules\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\UP68ER\Projects\testy\node_modules\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:796:13)
    at C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:556:49
    at runSingle (C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:137:13)
    at flush (C:\Users\UP68ER\Projects\testy\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
